# create PersistentVolume for mysql
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: manual-pv-mysql
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/mysql
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual

---
# create PersistentVolume for wordpress
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: manual-pv-wordpress
spec:
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/wordpress
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual