---
# create secret for mysql. create secure script using command: echo -n 'mysecretpassword' | base64
# create secret option can be skipped if created manually: kubectl create secret generic mysql-pass --from-literal=password=mysecretpassword

---
kind: Secret
apiVersion: v1
metadata:
  name: mysql-pass
type: Opaque
data:
  password: bXlzZWNyZXRwYXNzd29yZA==

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql     # this should match
  template:
    metadata:
      labels:
        app: mysql    # this should match
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
            - name: MYSQL_DATABASE
              value: wordpress
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim

---
kind: Service
apiVersion: v1
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
    - port: 3306