---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wp-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  volumeName: manual-pv-wordpress
  resources:
    requests:
      storage: 20Gi
